### ISSUE TITLE
This works but not quite for me.

### ISSUE THREAD

**Issue by dahjin** [yangshuairocks/Open_in_Windows_Terminal#1]
Whenever i use the context menu shortcut it will bring up the Console but it will take me to the default documents instead of say desktop.

**Comment by dahjin** [comment]
Gif for clarity
![CQ20hjC9X3](https://user-images.githubusercontent.com/8744819/73944797-2c756300-48c1-11ea-992d-289d94a702ac.gif)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
What Operating System are you using? 
Could you try run `set-executionpolicy bypass -force` in a PowerShell session and try again?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I've updated the usage note and the code. Please use the new code follow the instruction and see if it works.

**Comment by dahjin** [comment]
Yes this works! Thank you so much.
