### ISSUE TITLE
建议更改一下Microsoft.PowerShell_profile.ps1的设置方式

### ISSUE THREAD

**Issue by MomentDerek** [yangshuairocks/Open_in_Windows_Terminal#3]
非常有创意的方案，我看到的时候惊了，但是如果本身对powershell有初始化脚本的话就会有点小问题，望大佬解决

建议将原有的Microsoft.PowerShell_profile.ps1的内容转移到逻辑中去，或者转换成函数，不然可能会报错

我解决之后是这个样子的

![image](https://user-images.githubusercontent.com/40252940/74121607-2655ee00-4c03-11ea-93e2-a35ab739675c.png)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
我看了一下你的修改，你是在最后一次打开窗口（之前可能会flash一两次）的时候import了一些module。但是我想着你的profile里的东西在每次打开PowerShell窗口的时候总是会执行的呀，你加的这些设置PowerShell session的内容放在`#===Open in Windows Terminal start===#`之前可能更合适？

你说的报错能贴出具体错误信息看一下么？我在好几千行的Profile下测试并没有遇到什么错误呀。

**Comment by MomentDerek** [comment]
报错信息就是前面在import的时候，“#===Open in Windows Terminal start===#”这个直接接在上面，没有换行，导致的错误

**Comment by MomentDerek** [comment]
但是因为这整个调用的过程重复了三次，而我原来写的那些东西也重复被调用了三次，每次调用会占用不少时间，所以就把它挪进去了，嗯……后来发现影响到了正常启动，才发现自己脑抽了……现在是用函数的方式，在多处else后面调用

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
那把添加到Profile里的这些内容放在Profile在最前面，应该就不会有性能问题（一开始就判断是不是要重新打开PowerShell session），而且也不会出现`#===Open in Windows Terminal start===#`直接接在Profile内容最后一行的问题了吧？

**Comment by MomentDerek** [comment]
对的

**Comment by MomentDerek** [comment]
好像确实是这样hh，我搞复杂了

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
好的，有思路了我来改一下。

**Comment by MomentDerek** [comment]
嗯……还是要用函数来解决……一眼难尽，直接上图吧

![效果2](https://user-images.githubusercontent.com/40252940/74146591-5c639400-4c3c-11ea-9776-e7d0e144fd0e.gif)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
我修改了一下，应该解决了你说的性能问题了。

**Comment by MomentDerek** [comment]
确实解决了
