### ISSUE TITLE
可以在注册表内调用powershell的时候加入-WindowStyle Hidden参数，可以开的更加隐蔽

### ISSUE THREAD

**Issue by MomentDerek** [yangshuairocks/Open_in_Windows_Terminal#4]
![image](https://user-images.githubusercontent.com/40252940/74122273-7df55900-4c05-11ea-918f-72040e5f647e.png)

演示：
![效果](https://user-images.githubusercontent.com/40252940/74122527-8d28d680-4c06-11ea-92bf-338d1eb5777b.gif)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
谢谢提供信息，我没用过这个参数呢，我研究一下。

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
已经添加了，确实有效。
