### ISSUE TITLE
建议加入非管理员打开的选项

### ISSUE THREAD

**Issue by MomentDerek** [yangshuairocks/Open_in_Windows_Terminal#5]
毕竟没关UAC，每次打开变黑怪难受的

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
那你建议是怎么实现？另外加在右键菜单里加一个"Open in Windows Terminal (Non-admin)"，还是给出另一个安装文件，安装完后每次都是"Open in Windows Terminal (Non-admin)"，还是其他的什么方法？
我是全部用Run as Admin的，所以从来没考虑过这个，我想着如果在右键菜单里再加一个"Open in Windows Terminal (Non-admin)"好像有点奇怪。

**Comment by MomentDerek** [comment]
这个问题我解决了，大致说一下，大佬可以把它合并一下哈，我不擅长写这个，所以折腾了好久23333

## 主要目的：
在右键菜单中实现两个选项，用管理员权限打开和非管理员权限打开，如果不是非常需要管理员权限可以只用非管理员权限打开就行，干净利索些

## 思路：
额外用个临时文件记录打开类型，我写的这个是用windows_terminal_current_method.temp来记录

## 修改点
注册表里面的命令修改一下，从原来的直接输入命令改为执行脚本（比较好维护？），在我的电脑里面是这样的：`powershell -WindowStyle Hidden -File "E:\Moment的文件夹\Documents\WindowsPowerShell\PowerShell_openByAdmin.ps1" '%V'`

如果是非管理员就是这样：`powershell -WindowStyle Hidden -File "E:\Moment的文件夹\Documents\WindowsPowerShell\PowerShell_openByNoAdmin.ps1" '%V'`

然后增加两个脚本在powershell的配置文件文件夹，就是上面的那两个，如果大佬能将这两个脚本改为命令的话最好，因为只要调用脚本就会触发初始化的那个脚本，就会有漫长的加载……我增加了一个判断条件——只要存在windows_terminal_current_dir.temp就不进行那个冗长的加载过程，所以只要在注册表里的调用不经过脚本，后面的那些中间过程就不会有那种冗长的加载了（在大佬解决前我就当powershell不存在，只用WindowsTerminal里面的就好了）

初始化脚本里面有个小问题，可能只存在于部分的powershell中，就是在设置路径的时候，可能会因为单引号而导致错误，所以我加了一句话把单引号去掉了

三个脚本我打了个包在附件里，大佬查收一下

[WindowsPowerShell.zip](https://github.com/yangshuairocks/Open_in_Windows_Terminal/files/4180781/WindowsPowerShell.zip)

## 效果
上两个图演示一下大致效果

正常打开：
![效果3](https://user-images.githubusercontent.com/40252940/74150395-caac5480-4c44-11ea-8781-d135dd3d0260.gif)

管理员权限打开（中间停顿的时候就是我去点UAC了，录屏录不到）：
![效果4](https://user-images.githubusercontent.com/40252940/74150627-45756f80-4c45-11ea-9208-df8902eae2b7.gif)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
谢谢提供的信息。这个功能已经添加了，具体可以看我更新的README。

**Comment by MomentDerek** [comment]
嗯嗯，实验过ok了
