### ISSUE TITLE
添加子选项以管理员模式打开

### ISSUE THREAD

**Issue by lisonge** [yangshuairocks/Open_in_Windows_Terminal#7]
![image](https://user-images.githubusercontent.com/38517192/75105780-d2132b00-5652-11ea-8a4b-03475a0f663d.png)

**Comment by KUTlime** [comment]
[看这里](https://github.com/KUTlime/PowerShell-Open-Here-Module)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
谢谢提供信息啊，看起来很不错，我试试去
